blank_issues_enabled: false
contact_links:
  - name: Questions? Ask them using discussions
    url: https://github.com/Jelmerro/Vieb/discussions/categories/q-a
    about: Open the Q&A section on Github discussions
  - name: Show what you made using Vieb
    url: https://github.com/Jelmerro/Vieb/discussions/categories/show-and-tell
    about: Open the show and tell section of Github discussions
  - name: Share a bright idea with the community on Github
    url: https://github.com/Jelmerro/Vieb/discussions/categories/ideas
    about: Open the Ideas section of Github discussions
  - name: Chat or ask on Telegram
    url: https://t.me/vieb_general
    about: Open the general Telegram chat of Vieb
  - name: Chat or ask on Matrix
    url: https://matrix.to/#/#vieb:matrix.org
    about: Open the matrix space to chat
