/*
* Vieb - Vim Inspired Electron Browser
* Copyright (C) 2024 Jelmer van Arnhem
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/** @type {{[mode: string]: {
 *   [key: string]: {mapping: string, noremap?: boolean}
 * }}} */
export const defaultBindings = {
    "c": {
        "<C-[>": {"mapping": "<toNormalMode>"},
        "<C-i>": {"mapping": "<editWithVim>"},
        "<C-j>": {"mapping": "<nextSuggestion>"},
        "<C-k>": {"mapping": "<prevSuggestion>"},
        "<C-n>": {"mapping": "<commandHistoryNext>"},
        "<C-p>": {"mapping": "<commandHistoryPrevious>"},
        "<CR>": {"mapping": "<useEnteredData>"},
        "<Down>": {"mapping": "<nextSuggestion>"},
        "<Esc>": {"mapping": "<toNormalMode>"},
        "<F2>": {"mapping": "<toNormalMode>"},
        "<S-Tab>": {"mapping": "<prevSuggestion>"},
        "<Tab>": {"mapping": "<nextSuggestion>"},
        "<Up>": {"mapping": "<prevSuggestion>"},
        "<kClear>": {"mapping": "<useEnteredData>"},
        "<kDown>": {"mapping": "<nextSuggestion>"},
        "<kEnter>": {"mapping": "<useEnteredData>"},
        "<kUp>": {"mapping": "<prevSuggestion>"}
    },
    "e": {
        "<C-[>": {"mapping": "<toNormalMode>"},
        "<C-Down>": {"mapping": "<nextSuggestionSection>"},
        "<C-Up>": {"mapping": "<prevSuggestionSection>"},
        "<C-i>": {"mapping": "<editWithVim>"},
        "<C-j>": {"mapping": "<nextSuggestion>"},
        "<C-k>": {"mapping": "<prevSuggestion>"},
        "<C-kDown>": {"mapping": "<nextSuggestionSection>"},
        "<C-kUp>": {"mapping": "<prevSuggestionSection>"},
        "<C-n>": {"mapping": "<exploreHistoryNext>"},
        "<C-p>": {"mapping": "<exploreHistoryPrevious>"},
        "<CR>": {"mapping": "<useEnteredData>"},
        "<Down>": {"mapping": "<nextSuggestion>"},
        "<Esc>": {"mapping": "<toNormalMode>"},
        "<F6>": {"mapping": "<toNormalMode>"},
        "<PageDown>": {"mapping": "<nextSuggestionSection>"},
        "<PageUp>": {"mapping": "<prevSuggestionSection>"},
        "<S-Tab>": {"mapping": "<prevSuggestion>"},
        "<Tab>": {"mapping": "<nextSuggestion>"},
        "<Up>": {"mapping": "<prevSuggestion>"},
        "<kClear>": {"mapping": "<useEnteredData>"},
        "<kDown>": {"mapping": "<nextSuggestion>"},
        "<kEnter>": {"mapping": "<useEnteredData>"},
        "<kPageDown>": {"mapping": "<nextSuggestionSection>"},
        "<kPageUp>": {"mapping": "<prevSuggestionSection>"},
        "<kUp>": {"mapping": "<prevSuggestion>"}
    },
    "f": {
        "<C-[>": {"mapping": "<stopFollowMode>"},
        "<Esc>": {"mapping": "<stopFollowMode>"},
        "<F4>": {"mapping": "<stopFollowMode>"},
        "<Tab>": {"mapping": "<reorderFollowLinks>"},
        "`": {"mapping": "<:set followlabelposition!>"}
    },
    "i": {
        "<C-[>": {"mapping": "<toNormalMode>"},
        "<C-i>": {"mapping": "<editWithVim>"},
        "<CapsLock>": {"mapping": "<nop>"},
        "<Esc>": {"mapping": "<toNormalMode>"},
        "<NumLock>": {"mapping": "<nop>"},
        "<ScrollLock>": {"mapping": "<nop>"}
    },
    "m": {
        ".": {"mapping": "<repeatLastAction>"},
        "<C-[>": {"mapping": "<menuClose>"},
        "<C-Down>": {"mapping": "<menuSectionDown>"},
        "<C-Up>": {"mapping": "<menuSectionUp>"},
        "<C-kDown>": {"mapping": "<menuSectionDown>"},
        "<C-kUp>": {"mapping": "<menuSectionUp>"},
        "<C-n>": {"mapping": "<menuDown>"},
        "<C-p>": {"mapping": "<menuUp>"},
        "<CR>": {"mapping": "<menuSelect>"},
        "<Down>": {"mapping": "<menuDown>"},
        "<End>": {"mapping": "<menuBottom>"},
        "<Esc>": {"mapping": "<menuClose>"},
        "<Home>": {"mapping": "<menuTop>"},
        "<PageDown>": {"mapping": "<menuSectionDown>"},
        "<PageUp>": {"mapping": "<menuSectionUp>"},
        "<S-Tab>": {"mapping": "<menuSectionUp>"},
        "<Tab>": {"mapping": "<menuSectionDown>"},
        "<Up>": {"mapping": "<menuUp>"},
        "<kClear>": {"mapping": "<menuSelect>"},
        "<kDown>": {"mapping": "<menuDown>"},
        "<kEnd>": {"mapping": "<menuBottom>"},
        "<kEnter>": {"mapping": "<menuSelect>"},
        "<kHome>": {"mapping": "<menuTop>"},
        "<kPageDown>": {"mapping": "<menuSectionDown>"},
        "<kPageUp>": {"mapping": "<menuSectionUp>"},
        "<kUp>": {"mapping": "<menuUp>"},
        "H": {"mapping": "<menuTop>"},
        "L": {"mapping": "<menuBottom>"}
    },
    "n": {
        "\"<Any>": {"mapping": "<restoreMark>"},
        "$": {"mapping": "<scrollRightMax>"},
        "'<Any>": {"mapping": "<restoreScrollPos>"},
        "+": {"mapping": "<zoomIn>"},
        ".": {"mapping": "<repeatLastAction>"},
        "/": {"mapping": "<toSearchMode>"},
        ":": {"mapping": "<toCommandMode>"},
        ";": {"mapping": "<toCommandMode>"},
        "<BS>": {"mapping": "<emptySearch>"},
        "<C-[>": {"mapping": "<stopLoadingPage>"},
        "<C-Left>": {"mapping": "<backInHistory>"},
        "<C-Right>": {"mapping": "<forwardInHistory>"},
        "<C-a>": {"mapping": "<increasePageNumber>"},
        "<C-b>": {"mapping": "<scrollPageUp>"},
        "<C-c>": {"mapping": "<p.copyText>"},
        "<C-d>": {"mapping": "<scrollPageDownHalf>"},
        "<C-e>": {"mapping": "<scrollDown>"},
        "<C-f>": {"mapping": "<scrollPageDown>"},
        "<C-i>": {"mapping": "<forwardInHistory>"},
        "<C-j>": {"mapping": "<moveTabForward>"},
        "<C-k>": {"mapping": "<moveTabBackward>"},
        "<C-kPageDown>": {"mapping": "<nextTab>"},
        "<C-kPageUp>": {"mapping": "<previousTab>"},
        "<C-l>": {"mapping": "<toExploreMode>"},
        "<C-n>": {"mapping": "<nextTab>"},
        "<C-o>": {"mapping": "<backInHistory>"},
        "<C-p>": {"mapping": "<previousTab>"},
        "<C-t>": {"mapping": "<:set tabnewposition=end>"
            + "<:tabnew><:set tabnewposition=right>"},
        "<C-u>": {"mapping": "<scrollPageUpHalf>"},
        "<C-w>+": {"mapping": "<increaseHeightSplitWindow>"},
        "<C-w><C-=>": {"mapping": "<distrubuteSpaceSplitWindow>"},
        "<C-w><C->>": {"mapping": "<increaseWidthSplitWindow>"},
        "<C-w><C-H>": {"mapping": "<leftHalfSplitWindow>"},
        "<C-w><C-J>": {"mapping": "<bottomHalfSplitWindow>"},
        "<C-w><C-K>": {"mapping": "<topHalfSplitWindow>"},
        "<C-w><C-L>": {"mapping": "<rightHalfSplitWindow>"},
        "<C-w><C-R>": {"mapping": "<rotateSplitWindowBackward>"},
        "<C-w><C-W>": {"mapping": "<toPreviousSplitWindow>"},
        "<C-w><C-b>": {"mapping": "<toLastSplitWindow>"},
        "<C-w><C-c>": {"mapping": "<:close>"},
        "<C-w><C-h>": {"mapping": "<toLeftSplitWindow>"},
        "<C-w><C-j>": {"mapping": "<toBottomSplitWindow>"},
        "<C-w><C-k>": {"mapping": "<toTopSplitWindow>"},
        "<C-w><C-l>": {"mapping": "<toRightSplitWindow>"},
        "<C-w><C-lt>": {"mapping": "<decreaseWidthSplitWindow>"},
        "<C-w><C-n>": {"mapping": "<:split>"},
        "<C-w><C-o>": {"mapping": "<:only>"},
        "<C-w><C-p>": {"mapping": "<:buffer #>"},
        "<C-w><C-q>": {"mapping": "<:quit>"},
        "<C-w><C-r>": {"mapping": "<rotateSplitWindowForward>"},
        "<C-w><C-s>": {"mapping": "<:split>"},
        "<C-w><C-t>": {"mapping": "<toFirstSplitWindow>"},
        "<C-w><C-v>": {"mapping": "<:vsplit>"},
        "<C-w><C-w>": {"mapping": "<toNextSplitWindow>"},
        "<C-w><C-x>": {"mapping": "<exchangeSplitWindow>"},
        "<C-w><lt>": {"mapping": "<decreaseWidthSplitWindow>"},
        "<C-w>=": {"mapping": "<distrubuteSpaceSplitWindow>"},
        "<C-w>>": {"mapping": "<increaseWidthSplitWindow>"},
        "<C-w>-": {"mapping": "<decreaseHeightSplitWindow>"},
        "<C-w>H": {"mapping": "<leftHalfSplitWindow>"},
        "<C-w>J": {"mapping": "<bottomHalfSplitWindow>"},
        "<C-w>K": {"mapping": "<topHalfSplitWindow>"},
        "<C-w>L": {"mapping": "<rightHalfSplitWindow>"},
        "<C-w>R": {"mapping": "<rotateSplitWindowBackward>"},
        "<C-w>W": {"mapping": "<toPreviousSplitWindow>"},
        "<C-w>b": {"mapping": "<toLastSplitWindow>"},
        "<C-w>c": {"mapping": "<:close>"},
        "<C-w>h": {"mapping": "<toLeftSplitWindow>"},
        "<C-w>j": {"mapping": "<toBottomSplitWindow>"},
        "<C-w>k": {"mapping": "<toTopSplitWindow>"},
        "<C-w>l": {"mapping": "<toRightSplitWindow>"},
        "<C-w>n": {"mapping": "<:split>"},
        "<C-w>o": {"mapping": "<:only>"},
        "<C-w>p": {"mapping": "<:buffer #>"},
        "<C-w>q": {"mapping": "<:quit>"},
        "<C-w>r": {"mapping": "<rotateSplitWindowForward>"},
        "<C-w>s": {"mapping": "<:split>"},
        "<C-w>t": {"mapping": "<toFirstSplitWindow>"},
        "<C-w>v": {"mapping": "<:vsplit>"},
        "<C-w>w": {"mapping": "<toNextSplitWindow>"},
        "<C-w>x": {"mapping": "<exchangeSplitWindow>"},
        "<C-x>": {"mapping": "<decreasePageNumber>"},
        "<C-y>": {"mapping": "<scrollUp>"},
        "<CR>": {"mapping": "<clickOnSearch>"},
        "<Down>": {"mapping": "<scrollDown>"},
        "<End>": {"mapping": "<scrollBottom>"},
        "<Esc>": {"mapping": "<stopLoadingPage>"},
        "<Home>": {"mapping": "<scrollTop>"},
        "<Left>": {"mapping": "<scrollLeft>"},
        "<PageDown>": {"mapping": "<scrollPageDown>"},
        "<PageUp>": {"mapping": "<scrollPageUp>"},
        "<Right>": {"mapping": "<scrollRight>"},
        "<Up>": {"mapping": "<scrollUp>"},
        "<k0>": {"mapping": "<scrollLeftMax>"},
        "<kClear>": {"mapping": "<clickOnSearch>"},
        "<kDivide>": {"mapping": "<toSearchMode>"},
        "<kDown>": {"mapping": "<scrollDown>"},
        "<kEnd>": {"mapping": "<scrollBottom>"},
        "<kEnter>": {"mapping": "<clickOnSearch>"},
        "<kHome>": {"mapping": "<scrollTop>"},
        "<kLeft>": {"mapping": "<scrollLeft>"},
        "<kMinus>": {"mapping": "<zoomOut>"},
        "<kPageDown>": {"mapping": "<scrollPageDown>"},
        "<kPageUp>": {"mapping": "<scrollPageUp>"},
        "<kPlus>": {"mapping": "<zoomIn>"},
        "<kRight>": {"mapping": "<scrollRight>"},
        "<kUp>": {"mapping": "<scrollUp>"},
        "=": {"mapping": "<zoomIn>"},
        "?": {"mapping": "<toSearchMode>"},
        "@:": {"mapping": "<toCommandMode><commandHistoryPrevious>"
            + "<useEnteredData>"},
        "@<Any>": {"mapping": "<runRecording>"},
        "[": {"mapping": "<previousPage>"},
        "]": {"mapping": "<nextPage>"},
        "^": {"mapping": "<scrollLeftMax>"},
        "_": {"mapping": "<zoomOut>"},
        "{": {"mapping": "<previousPageNewTab>"},
        "}": {"mapping": "<nextPageNewTab>"},
        "-": {"mapping": "<zoomOut>"},
        "0": {"mapping": "<scrollLeftMax>"},
        "BB": {"mapping": "<:buffer #>"},
        "BD": {"mapping": "<:close #>"},
        "BH": {"mapping": "<:hide #>"},
        "BS": {"mapping": "<:Sexplore #>"},
        "BV": {"mapping": "<:Vexplore #>"},
        "BZ": {"mapping": "<:suspend #>"},
        "D": {"mapping": "<downloadLink>"},
        "E": {"mapping": "<:tabnew><toExploreMode>"},
        "F": {"mapping": "<startFollowNewTab>"},
        "G": {"mapping": "<scrollBottom>"},
        "H": {"mapping": "<backInHistory>"},
        "I": {"mapping": "<moveTabStart>"},
        "J": {"mapping": "<nextTab>"},
        "K": {"mapping": "<previousTab>"},
        "L": {"mapping": "<forwardInHistory>"},
        "M<Any>": {"mapping": "<makeMark>"},
        "N": {"mapping": "<previousSearchMatch>"},
        "O": {"mapping": "<moveTabEnd>"},
        "P": {"mapping": "<:tabnew><openFromClipboard>"},
        "R": {"mapping": "<refreshTabWithoutCache>"},
        "S": {"mapping": "<startFollowNewSplit>"},
        "T": {"mapping": "<openNewTabWithCurrentUrl>"},
        "V": {"mapping": "<startFollowNewVerSplit>"},
        "ZZ": {"mapping": "<:quit>"},
        "b": {"mapping": "<previousTab>"},
        "c": {"mapping": "<p.start>"},
        "d": {"mapping": "<:close>"},
        "e": {"mapping": "<toExploreMode>"},
        "f": {"mapping": "<startFollowCurrentTab>"},
        "g<C-a>": {"mapping": "<increasePortNumber>"},
        "g<C-x>": {"mapping": "<decreasePortNumber>"},
        "gF": {"mapping": "<toggleSourceViewerNewTab>"},
        "gM": {"mapping": "<toggleMarkdownViewerNewTab>"},
        "gR": {"mapping": "<toggleReaderViewNewTab>"},
        "gS": {"mapping": "<toRootSubdomain>"},
        "gT": {"mapping": "<previousTab>"},
        "gU": {"mapping": "<toRootUrl>"},
        "gc": {"mapping": "<toggleTOC>"},
        "gf": {"mapping": "<toggleSourceViewer>"},
        "gg": {"mapping": "<scrollTop>"},
        "gi": {"mapping": "<insertAtFirstInput>"},
        "gm": {"mapping": "<toggleMarkdownViewer>"},
        "gr": {"mapping": "<toggleReaderView>"},
        "gs": {"mapping": "<toParentSubdomain>"},
        "gt": {"mapping": "<nextTab>"},
        "gu": {"mapping": "<toParentUrl>"},
        "gv": {"mapping": "<p.restoreSelection>"},
        "h": {"mapping": "<scrollLeft>"},
        "i": {"mapping": "<toInsertMode>"},
        "j": {"mapping": "<scrollDown>"},
        "k": {"mapping": "<scrollUp>"},
        "l": {"mapping": "<scrollRight>"},
        "m<Any>": {"mapping": "<storeScrollPos>"},
        "n": {"mapping": "<nextSearchMatch>"},
        "p": {"mapping": "<openFromClipboard>"},
        "q": {"mapping": "<stopRecording><:nmap q<Any> <:nunmap q<Any>>"
            + "<:punmap q<Any>><:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>><:vunmap q<Esc>>"
            + "<startRecording>><:pmap q<Any> <:nunmap q<Any>>"
            + "<:punmap q<Any>><:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>><:vunmap q<Esc>>"
            + "<startRecording>><:vmap q<Any> <:nunmap q<Any>>"
            + "<:punmap q<Any>><:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>><:vunmap q<Esc>>"
            + "<startRecording>>"
            + "<:nmap q<C-[> <nop>><:pmap q<C-[> <nop>><:vmap q<C-[> <nop>>"
            + "<:nmap q<Esc> <nop>><:pmap q<Esc> <nop>><:vmap q<Esc> <nop>>"},
        "q<Any>": {"mapping": "<:nunmap q<Any>><:punmap q<Any>>"
            + "<:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>>"
            + "<:vunmap q<Esc>><startRecording>"},
        "q<C-[>": {"mapping": "<nop>"},
        "q<Esc>": {"mapping": "<nop>"},
        "r": {"mapping": "<refreshTab>"},
        "s": {"mapping": "<p.moveToMouse>"},
        "t": {"mapping": "<:tabnew>"},
        "u": {"mapping": "<reopenTab>"},
        "v": {"mapping": "<p.start>"},
        "w": {"mapping": "<nextTab>"},
        "x": {"mapping": "<openLinkExternal>"},
        "yR<Any>": {"mapping": "<pageRSSLinkToClipboard>"},
        "yRL": {"mapping": "<pageRSSLinksList>"},
        "ye": {"mapping": "<pageToClipboardEmacs>"},
        "yf": {"mapping": "<startFollowCopyLink>"},
        "yh": {"mapping": "<pageToClipboardHTML>"},
        "ym": {"mapping": "<pageToClipboardMarkdown>"},
        "yr": {"mapping": "<pageToClipboardRST>"},
        "ys": {"mapping": "<p.copyText>"},
        "yt": {"mapping": "<pageTitleToClipboard>"},
        "yy": {"mapping": "<pageToClipboard>"},
        "zH": {"mapping": "<scrollPageLeft>"},
        "zL": {"mapping": "<scrollPageRight>"},
        "zh": {"mapping": "<scrollLeft>"},
        "zl": {"mapping": "<scrollRight>"},
        "zm": {"mapping": "<:mute>"},
        "zp": {"mapping": "<:pin>"}
    },
    "p": {
        "\"<Any>": {"mapping": "<p.restorePos>"},
        "$": {"mapping": "<p.moveRightMax>"},
        "'<Any>": {"mapping": "<p.restorePos>"},
        "*": {"mapping": "<p.vsplitLink>"},
        ".": {"mapping": "<repeatLastAction>"},
        "<C-[>": {"mapping": "<toNormalMode>"},
        "<C-End>": {"mapping": "<p.endOfPage>"},
        "<C-Home>": {"mapping": "<p.startOfPage>"},
        "<C-Left>": {"mapping": "<p.moveFastLeft>"},
        "<C-Right>": {"mapping": "<p.moveFastRight>"},
        "<C-b>": {"mapping": "<scrollPageUp>"},
        "<C-c>": {"mapping": "<p.copyText>"},
        "<C-d>": {"mapping": "<p.moveFastDown>"},
        "<C-f>": {"mapping": "<scrollPageDown>"},
        "<C-h>": {"mapping": "<p.moveSlowLeft>"},
        "<C-j>": {"mapping": "<p.moveSlowDown>"},
        "<C-k>": {"mapping": "<p.moveSlowUp>"},
        "<C-kEnd>": {"mapping": "<p.endOfPage>"},
        "<C-kHome>": {"mapping": "<p.startOfPage>"},
        "<C-kLeft>": {"mapping": "<p.moveFastLeft>"},
        "<C-kRight>": {"mapping": "<p.moveFastRight>"},
        "<C-l>": {"mapping": "<p.moveSlowRight>"},
        "<C-u>": {"mapping": "<p.moveFastUp>"},
        "<CR>": {"mapping": "<p.leftClick>"},
        "<Down>": {"mapping": "<p.moveDown>"},
        "<End>": {"mapping": "<p.moveRightMax>"},
        "<Esc>": {"mapping": "<toNormalMode>"},
        "<F7>": {"mapping": "<toNormalMode>"},
        "<Home>": {"mapping": "<p.moveLeftMax>"},
        "<Left>": {"mapping": "<p.moveLeft>"},
        "<Right>": {"mapping": "<p.moveRight>"},
        "<S-CR>": {"mapping": "<p.newtabLink>"},
        "<S-kClear>": {"mapping": "<p.newtabLink>"},
        "<S-kEnter>": {"mapping": "<p.newtabLink>"},
        "<Up>": {"mapping": "<p.moveUp>"},
        "<k0>": {"mapping": "<p.moveLeftMax>"},
        "<kClear>": {"mapping": "<p.leftClick>"},
        "<kDown>": {"mapping": "<p.moveDown>"},
        "<kEnd>": {"mapping": "<p.moveRightMax>"},
        "<kEnter>": {"mapping": "<p.leftClick>"},
        "<kHome>": {"mapping": "<p.moveLeftMax>"},
        "<kLeft>": {"mapping": "<p.moveLeft>"},
        "<kRight>": {"mapping": "<p.moveRight>"},
        "<kUp>": {"mapping": "<p.moveUp>"},
        "<lt>": {"mapping": "<p.scrollLeft>"},
        ">": {"mapping": "<p.scrollRight>"},
        "@<Any>": {"mapping": "<runRecording>"},
        "[": {"mapping": "<p.scrollUp>"},
        "]": {"mapping": "<p.scrollDown>"},
        "^": {"mapping": "<p.moveLeftMax>"},
        "0": {"mapping": "<p.moveLeftMax>"},
        "B": {"mapping": "<p.moveFastLeft>"},
        "D": {"mapping": "<p.downloadLink>"},
        "G": {"mapping": "<p.endOfPage>"},
        "H": {"mapping": "<p.startOfView>"},
        "J": {"mapping": "<p.scrollDown>"},
        "K": {"mapping": "<p.scrollUp>"},
        "L": {"mapping": "<p.endOfView>"},
        "M": {"mapping": "<p.centerOfView>"},
        "N": {"mapping": "<previousSearchMatch>"},
        "SA": {"mapping": "<p.splitAudio>"},
        "SF": {"mapping": "<p.splitFrame>"},
        "SI": {"mapping": "<p.splitImage>"},
        "SL": {"mapping": "<p.splitLink>"},
        "SS": {"mapping": "<p.splitLink>"},
        "SV": {"mapping": "<p.splitVideo>"},
        "Sa": {"mapping": "<p.splitAudio>"},
        "Sf": {"mapping": "<p.splitFrame>"},
        "Si": {"mapping": "<p.splitImage>"},
        "Sl": {"mapping": "<p.splitLink>"},
        "Ss": {"mapping": "<p.splitLink>"},
        "Sv": {"mapping": "<p.splitVideo>"},
        "VA": {"mapping": "<p.vsplitAudio>"},
        "VF": {"mapping": "<p.vsplitFrame>"},
        "VI": {"mapping": "<p.vsplitImage>"},
        "VL": {"mapping": "<p.vsplitLink>"},
        "VS": {"mapping": "<p.vsplitLink>"},
        "VV": {"mapping": "<p.vsplitVideo>"},
        "Va": {"mapping": "<p.vsplitAudio>"},
        "Vf": {"mapping": "<p.vsplitFrame>"},
        "Vi": {"mapping": "<p.vsplitImage>"},
        "Vl": {"mapping": "<p.vsplitLink>"},
        "Vs": {"mapping": "<p.vsplitLink>"},
        "Vv": {"mapping": "<p.vsplitVideo>"},
        "W": {"mapping": "<p.moveFastRight>"},
        "a<Any>": {"mapping": "<p.storePos>"},
        "b": {"mapping": "<p.moveFastLeft>"},
        "da": {"mapping": "<p.downloadAudio>"},
        "dd": {"mapping": "<p.downloadLink>"},
        "df": {"mapping": "<p.downloadFrame>"},
        "di": {"mapping": "<p.downloadImage>"},
        "dl": {"mapping": "<p.downloadLink>"},
        "dv": {"mapping": "<p.downloadVideo>"},
        "e": {"mapping": "<p.inspectElement>"},
        "f": {"mapping": "<startFollowCurrentTab>"},
        "gg": {"mapping": "<p.startOfPage>"},
        "gv": {"mapping": "<p.restoreSelection>"},
        "h": {"mapping": "<p.moveLeft>"},
        "i": {"mapping": "<p.insertAtPosition>"},
        "j": {"mapping": "<p.moveDown>"},
        "k": {"mapping": "<p.moveUp>"},
        "l": {"mapping": "<p.moveRight>"},
        "mc": {"mapping": "<p.toggleMediaControls>"},
        "md": {"mapping": "<p.mediaDown>"},
        "mf": {"mapping": "<p.mediaFaster>"},
        "ml": {"mapping": "<p.toggleMediaLoop>"},
        "mm": {"mapping": "<p.toggleMediaMute>"},
        "mp": {"mapping": "<p.toggleMediaPlay>"},
        "ms": {"mapping": "<p.mediaSlower>"},
        "mu": {"mapping": "<p.mediaUp>"},
        "n": {"mapping": "<nextSearchMatch>"},
        "oa": {"mapping": "<p.openAudio>"},
        "of": {"mapping": "<p.openFrame>"},
        "oi": {"mapping": "<p.openImage>"},
        "ol": {"mapping": "<p.openLink>"},
        "oo": {"mapping": "<p.openLink>"},
        "ov": {"mapping": "<p.openVideo>"},
        "q": {"mapping": "<stopRecording><:nmap q<Any> <:nunmap q<Any>>"
            + "<:punmap q<Any>><:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>><:vunmap q<Esc>>"
            + "<startRecording>><:pmap q<Any> <:nunmap q<Any>>"
            + "<:punmap q<Any>><:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>><:vunmap q<Esc>>"
            + "<startRecording>><:vmap q<Any> <:nunmap q<Any>>"
            + "<:punmap q<Any>><:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>><:vunmap q<Esc>>"
            + "<startRecording>>"
            + "<:nmap q<C-[> <nop>><:pmap q<C-[> <nop>><:vmap q<C-[> <nop>>"
            + "<:nmap q<Esc> <nop>><:pmap q<Esc> <nop>><:vmap q<Esc> <nop>>"},
        "q<Any>": {"mapping": "<:nunmap q<Any>><:punmap q<Any>>"
            + "<:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>>"
            + "<:vunmap q<Esc>><startRecording>"},
        "q<C-[>": {"mapping": "<nop>"},
        "q<Esc>": {"mapping": "<nop>"},
        "r": {"mapping": "<p.rightClick>"},
        "s": {"mapping": "<p.moveToMouse>"},
        "ta": {"mapping": "<p.newtabAudio>"},
        "tf": {"mapping": "<p.newtabFrame>"},
        "ti": {"mapping": "<p.newtabImage>"},
        "tl": {"mapping": "<p.newtabLink>"},
        "tn": {"mapping": "<p.newtabLink>"},
        "tv": {"mapping": "<p.newtabVideo>"},
        "v": {"mapping": "<p.startVisualSelect>"},
        "w": {"mapping": "<p.moveFastRight>"},
        "xa": {"mapping": "<p.externalAudio>"},
        "xf": {"mapping": "<p.externalFrame>"},
        "xi": {"mapping": "<p.externalImage>"},
        "xl": {"mapping": "<p.externalLink>"},
        "xv": {"mapping": "<p.externalVideo>"},
        "xx": {"mapping": "<p.externalLink>"},
        "yI": {"mapping": "<p.copyImageBuffer>"},
        "yT": {"mapping": "<p.copyPageTitle>"},
        "ya": {"mapping": "<p.copyAudio>"},
        "yf": {"mapping": "<p.copyFrame>"},
        "yi": {"mapping": "<p.copyImage>"},
        "yl": {"mapping": "<p.copyLink>"},
        "yt": {"mapping": "<p.copyTitleAttr>"},
        "yv": {"mapping": "<p.copyVideo>"},
        "yy": {"mapping": "<p.copyLink>"},
        "zH": {"mapping": "<scrollPageLeft>"},
        "zL": {"mapping": "<scrollPageRight>"},
        "zh": {"mapping": "<scrollLeft>"},
        "zl": {"mapping": "<scrollRight>"}
    },
    "s": {
        "<C-[>": {"mapping": "<toNormalMode>"},
        "<C-i>": {"mapping": "<editWithVim>"},
        "<C-j>": {"mapping": "<nextSuggestion>"},
        "<C-k>": {"mapping": "<prevSuggestion>"},
        "<CR>": {"mapping": "<useEnteredData>"},
        "<Esc>": {"mapping": "<toNormalMode>"},
        "<F3>": {"mapping": "<toNormalMode>"},
        "<kClear>": {"mapping": "<useEnteredData>"},
        "<kEnter>": {"mapping": "<useEnteredData>"}
    },
    "v": {
        "\"<Any>": {"mapping": "<p.restorePos>"},
        "$": {"mapping": "<p.moveRightMax>"},
        "'<Any>": {"mapping": "<p.restorePos>"},
        "*": {"mapping": "<p.searchText><toNormalMode>"},
        ".": {"mapping": "<repeatLastAction>"},
        "<C-[>": {"mapping": "<toNormalMode>"},
        "<C-End>": {"mapping": "<p.endOfPage>"},
        "<C-Home>": {"mapping": "<p.startOfPage>"},
        "<C-Left>": {"mapping": "<p.moveFastLeft>"},
        "<C-Right>": {"mapping": "<p.moveFastRight>"},
        "<C-b>": {"mapping": "<scrollPageUp>"},
        "<C-c>": {"mapping": "<p.copyText>"},
        "<C-d>": {"mapping": "<p.moveFastDown>"},
        "<C-f>": {"mapping": "<scrollPageDown>"},
        "<C-h>": {"mapping": "<p.moveSlowLeft>"},
        "<C-j>": {"mapping": "<p.moveSlowDown>"},
        "<C-k>": {"mapping": "<p.moveSlowUp>"},
        "<C-kEnd>": {"mapping": "<p.endOfPage>"},
        "<C-kHome>": {"mapping": "<p.startOfPage>"},
        "<C-kLeft>": {"mapping": "<p.moveFastLeft>"},
        "<C-kRight>": {"mapping": "<p.moveFastRight>"},
        "<C-l>": {"mapping": "<p.moveSlowRight>"},
        "<C-u>": {"mapping": "<p.moveFastUp>"},
        "<Down>": {"mapping": "<p.moveDown>"},
        "<End>": {"mapping": "<p.moveRightMax>"},
        "<Esc>": {"mapping": "<toNormalMode>"},
        "<F7>": {"mapping": "<toNormalMode>"},
        "<Home>": {"mapping": "<p.moveLeftMax>"},
        "<Left>": {"mapping": "<p.moveLeft>"},
        "<Right>": {"mapping": "<p.moveRight>"},
        "<Up>": {"mapping": "<p.moveUp>"},
        "<k0>": {"mapping": "<p.moveLeftMax>"},
        "<kDown>": {"mapping": "<p.moveDown>"},
        "<kEnd>": {"mapping": "<p.moveRightMax>"},
        "<kHome>": {"mapping": "<p.moveLeftMax>"},
        "<kLeft>": {"mapping": "<p.moveLeft>"},
        "<kMultiply>": {"mapping": "<p.searchText><toNormalMode>"},
        "<kRight>": {"mapping": "<p.moveRight>"},
        "<kUp>": {"mapping": "<p.moveUp>"},
        "<lt>": {"mapping": "<p.scrollLeft>"},
        ">": {"mapping": "<p.scrollRight>"},
        "@<Any>": {"mapping": "<runRecording>"},
        "[": {"mapping": "<p.scrollUp>"},
        "]": {"mapping": "<p.scrollDown>"},
        "^": {"mapping": "<p.moveLeftMax>"},
        "0": {"mapping": "<p.moveLeftMax>"},
        "B": {"mapping": "<p.moveFastLeft>"},
        "G": {"mapping": "<p.endOfPage>"},
        "H": {"mapping": "<p.startOfView>"},
        "J": {"mapping": "<p.scrollDown>"},
        "K": {"mapping": "<p.scrollUp>"},
        "L": {"mapping": "<p.endOfView>"},
        "M": {"mapping": "<p.centerOfView>"},
        "W": {"mapping": "<p.moveFastRight>"},
        "a<Any>": {"mapping": "<p.storePos>"},
        "b": {"mapping": "<p.moveFastLeft>"},
        "c": {"mapping": "<toNormalMode><p.start>"},
        "f": {"mapping": "<startFollowCurrentTab>"},
        "gg": {"mapping": "<p.startOfPage>"},
        "h": {"mapping": "<p.moveLeft>"},
        "j": {"mapping": "<p.moveDown>"},
        "k": {"mapping": "<p.moveUp>"},
        "l": {"mapping": "<p.moveRight>"},
        "o": {"mapping": "<p.swapPosition>"},
        "q": {"mapping": "<stopRecording><:nmap q<Any> <:nunmap q<Any>>"
            + "<:punmap q<Any>><:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>><:vunmap q<Esc>>"
            + "<startRecording>><:pmap q<Any> <:nunmap q<Any>>"
            + "<:punmap q<Any>><:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>><:vunmap q<Esc>>"
            + "<startRecording>><:vmap q<Any> <:nunmap q<Any>>"
            + "<:punmap q<Any>><:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>><:vunmap q<Esc>>"
            + "<startRecording>>"
            + "<:nmap q<C-[> <nop>><:pmap q<C-[> <nop>><:vmap q<C-[> <nop>>"
            + "<:nmap q<Esc> <nop>><:pmap q<Esc> <nop>><:vmap q<Esc> <nop>>"},
        "q<Any>": {"mapping": "<:nunmap q<Any>><:punmap q<Any>>"
            + "<:vunmap q<Any>><:nunmap q<C-[>><:punmap q<C-[>>"
            + "<:vunmap q<C-[>><:nunmap q<Esc>><:punmap q<Esc>>"
            + "<:vunmap q<Esc>><startRecording>"},
        "q<C-[>": {"mapping": "<nop>"},
        "q<Esc>": {"mapping": "<nop>"},
        "r": {"mapping": "<p.rightClick>"},
        "s": {"mapping": "<p.moveToMouse>"},
        "tS": {"mapping": "<p.splitText>"},
        "tV": {"mapping": "<p.vsplitText>"},
        "td": {"mapping": "<p.downloadText><toNormalMode>"},
        "tn": {"mapping": "<p.newtabText>"},
        "to": {"mapping": "<p.openText><toNormalMode>"},
        "ts": {"mapping": "<p.searchText><toNormalMode>"},
        "tx": {"mapping": "<p.externalText><toNormalMode>"},
        "ty": {"mapping": "<p.copyText><toNormalMode>"},
        "w": {"mapping": "<p.moveFastRight>"},
        "y": {"mapping": "<p.copyText><toNormalMode>"},
        "zH": {"mapping": "<scrollPageLeft>"},
        "zL": {"mapping": "<scrollPageRight>"},
        "zh": {"mapping": "<scrollLeft>"},
        "zl": {"mapping": "<scrollRight>"}
    }
}
const globalDefaultMappings = {
    "<A-0>": {"mapping": "<:buffer -1>"},
    "<A-1>": {"mapping": "<:buffer 0>"},
    "<A-2>": {"mapping": "<:buffer 1>"},
    "<A-3>": {"mapping": "<:buffer 2>"},
    "<A-4>": {"mapping": "<:buffer 3>"},
    "<A-5>": {"mapping": "<:buffer 4>"},
    "<A-6>": {"mapping": "<:buffer 5>"},
    "<A-7>": {"mapping": "<:buffer 6>"},
    "<A-8>": {"mapping": "<:buffer 7>"},
    "<A-9>": {"mapping": "<:buffer 8>"},
    "<A-F4>": {"mapping": "<:quitall>"},
    "<A-Left>": {"mapping": "<backInHistory>"},
    "<A-Right>": {"mapping": "<forwardInHistory>"},
    "<A-m>": {"mapping": "<:mute>"},
    "<A-p>": {"mapping": "<:pin>"},
    "<C-+>": {"mapping": "<zoomIn>"},
    "<C-=>": {"mapping": "<zoomIn>"},
    "<C-_>": {"mapping": "<zoomOut>"},
    "<C-->": {"mapping": "<zoomOut>"},
    "<C-0>": {"mapping": "<zoomReset>"},
    "<C-F4>": {"mapping": "<:close>"},
    "<C-F5>": {"mapping": "<refreshTabWithoutCache>"},
    "<C-H>": {"mapping": "<:history>"},
    "<C-I>": {"mapping": "<:devtools>"},
    "<C-J>": {"mapping": "<:downloads>"},
    "<C-PageDown>": {"mapping": "<nextTab>"},
    "<C-PageUp>": {"mapping": "<previousTab>"},
    "<C-S-End>": {"mapping": "<moveTabEnd>"},
    "<C-S-Home>": {"mapping": "<moveTabStart>"},
    "<C-S-PageDown>": {"mapping": "<moveTabForward>"},
    "<C-S-PageUp>": {"mapping": "<moveTabBackward>"},
    "<C-S-Tab>": {"mapping": "<previousTab>"},
    "<C-S-kPageDown>": {"mapping": "<moveTabForward>"},
    "<C-S-kPageUp>": {"mapping": "<moveTabBackward>"},
    "<C-T>": {"mapping": "<reopenTab>"},
    "<C-Tab>": {"mapping": "<nextTab>"},
    "<C-Y>": {"mapping": "<:downloads>"},
    "<C-k0>": {"mapping": "<zoomReset>"},
    "<C-m>": {"mapping": "<menuOpen>"},
    "<C-q>": {"mapping": "<:quit>"},
    "<ContextMenu>": {"mapping": "<menuOpen>"},
    "<F1>": {"mapping": "<:help>"},
    "<F2>": {"mapping": "<toCommandMode>"},
    "<F3>": {"mapping": "<toSearchMode>"},
    "<F4>": {"mapping": "<startFollowCurrentTab>"},
    "<F5>": {"mapping": "<refreshTab>"},
    "<F6>": {"mapping": "<toExploreMode>"},
    "<F7>": {"mapping": "<p.start>"},
    "<F8>": {"mapping": "<:internaldevtools>"},
    "<F9>": {"mapping": "<nop>"},
    "<F10>": {"mapping": "<toggleAlwaysOnTop>"},
    "<F11>": {"mapping": "<toggleFullscreen>"},
    "<F12>": {"mapping": "<:devtools>"}
}
Object.keys(defaultBindings).forEach(mode => {
    Object.keys(globalDefaultMappings).forEach(key => {
        if (!defaultBindings[mode][key]) {
            defaultBindings[mode][key] = globalDefaultMappings[key]
        }
    })
})

export const keyNames = [
    {"js": ["<"], "vim": ["lt"]},
    {"js": ["Backspace"], "vim": ["BS"]},
    {
        "electron": "Return",
        "js": ["Enter", "\u000d"],
        "vim": ["CR", "NL", "Return", "Enter"]
    },
    {"js": ["|"], "vim": ["Bar"]},
    {"js": ["\\"], "vim": ["Bslash"]},
    {"electron": "Left", "js": ["ArrowLeft"], "vim": ["Left"]},
    {"electron": "Right", "js": ["ArrowRight"], "vim": ["Right"]},
    {"electron": "Up", "js": ["ArrowUp"], "vim": ["Up"]},
    {"electron": "Down", "js": ["ArrowDown"], "vim": ["Down"]},
    {"js": ["Escape", "Esc"], "vim": ["Esc"]},
    {"electron": "Space", "js": [" "], "vim": ["Space", " "]},
    {"js": ["Delete", "\u0000"], "vim": ["Del"]},
    {"js": ["PrintScreen"], "vim": ["PrintScreen", "PrtScr"]},
    {"js": ["Control"], "vim": ["Ctrl"]},
    {"electron": "Numlock", "js": ["NumLock"], "vim": ["NumLock"]},
    {"electron": "Capslock", "js": ["CapsLock"], "vim": ["CapsLock"]},
    {"electron": "Scrollock", "js": ["ScrollLock"], "vim": ["ScrollLock"]},
    {"electron": "Contextmenu", "js": ["ContextMenu"], "vim": ["ContextMenu"]},
    // Numpad keys
    {"electron": "Left", "js": ["kArrowLeft"], "vim": ["kLeft"]},
    {"electron": "Right", "js": ["kArrowRight"], "vim": ["kRight"]},
    {"electron": "Up", "js": ["kArrowUp"], "vim": ["kUp"]},
    {"electron": "Down", "js": ["kArrowDown"], "vim": ["kDown"]},
    {"electron": "numadd", "js": ["k+", "kPlus"], "vim": ["kPlus"]},
    {"electron": "numsub", "js": ["k-", "kMinus"], "vim": ["kMinus"]},
    {"electron": "nummult", "js": ["k*", "kMultiply"], "vim": ["kMultiply"]},
    {"electron": "numdiv", "js": ["k/", "kDivide"], "vim": ["kDivide"]},
    {"electron": "numdec", "js": ["k.", "kPoint"], "vim": ["kPoint"]},
    {"electron": "num0", "js": ["k0"], "vim": ["k0"]},
    {"electron": "num1", "js": ["k1"], "vim": ["k1"]},
    {"electron": "num2", "js": ["k2"], "vim": ["k2"]},
    {"electron": "num3", "js": ["k3"], "vim": ["k3"]},
    {"electron": "num4", "js": ["k4"], "vim": ["k4"]},
    {"electron": "num5", "js": ["k5"], "vim": ["k5"]},
    {"electron": "num6", "js": ["k6"], "vim": ["k6"]},
    {"electron": "num7", "js": ["k7"], "vim": ["k7"]},
    {"electron": "num8", "js": ["k8"], "vim": ["k8"]},
    {"electron": "num9", "js": ["k9"], "vim": ["k9"]},
    {"electron": "Delete", "js": ["kDelete"], "vim": ["kDel"]},
    {"electron": "Clear", "js": ["kClear"], "vim": ["kClear"]},
    {"electron": "Home", "js": ["kHome"], "vim": ["kHome"]},
    {"electron": "End", "js": ["kEnd"], "vim": ["kEnd"]},
    {"electron": "PageUp", "js": ["kPageUp"], "vim": ["kPageUp"]},
    {"electron": "PageDown", "js": ["kPageDown"], "vim": ["kPageDown"]},
    {"electron": "Return", "js": ["kEnter"], "vim": ["kEnter"]},
    {"electron": "Insert", "js": ["kInsert"], "vim": ["kInsert"]},
    // Keys with the same names, which are listed here to detect incorrect names
    // Note: some of these are not present in Vim and use the JavaScript name
    {"js": ["Shift"], "vim": ["Shift"]},
    {"js": ["Alt"], "vim": ["Alt"]},
    {"js": ["Meta"], "vim": ["Meta"]},
    {"js": ["F1"], "vim": ["F1"]},
    {"js": ["F2"], "vim": ["F2"]},
    {"js": ["F3"], "vim": ["F3"]},
    {"js": ["F4"], "vim": ["F4"]},
    {"js": ["F5"], "vim": ["F5"]},
    {"js": ["F6"], "vim": ["F6"]},
    {"js": ["F7"], "vim": ["F7"]},
    {"js": ["F8"], "vim": ["F8"]},
    {"js": ["F9"], "vim": ["F9"]},
    {"js": ["F10"], "vim": ["F10"]},
    {"js": ["F11"], "vim": ["F11"]},
    {"js": ["F12"], "vim": ["F12"]},
    {"js": ["Tab"], "vim": ["Tab"]},
    {"js": ["Insert"], "vim": ["Insert"]},
    {"js": ["Home"], "vim": ["Home"]},
    {"js": ["PageUp"], "vim": ["PageUp"]},
    {"js": ["End"], "vim": ["End"]},
    {"js": ["PageDown"], "vim": ["PageDown"]},
    {"js": ["Help"], "vim": ["Help"]},
    {"js": ["Pause"], "vim": ["Pause"]},
    // Fictional keys with custom implementation
    {"js": ["Any"], "vim": ["Any"]}
]

// Single use actions that do not need to be called multiple times if counted
export const uncountableActions = [
    "emptySearch",
    "clickOnSearch",
    "toExploreMode",
    "startFollowCopyLink",
    "startFollowCurrentTab",
    "startFollowNewTab",
    "startFollowNewSplit",
    "startFollowNewVerSplit",
    "scrollRightMax",
    "scrollLeftMax",
    "insertAtFirstInput",
    "toInsertMode",
    "refreshTab",
    "refreshTabWithoutCache",
    "moveTabEnd",
    "moveTabStart",
    "nextPage",
    "previousPage",
    "nextPageNewTab",
    "previousPageNewTab",
    "toRootUrl",
    "toSearchMode",
    "openNewTabWithCurrentUrl",
    "toCommandMode",
    "stopLoadingPage",
    "zoomReset",
    "toNormalMode",
    "stopFollowMode",
    "editWithVim",
    "leftHalfSplitWindow",
    "bottomHalfSplitWindow",
    "topHalfSplitWindow",
    "rightHalfSplitWindow",
    "toFirstSplitWindow",
    "toLastSplitWindow",
    "distrubuteSpaceSplitWindow",
    "pageRSSLinkToClipboard",
    "pageRSSLinksList",
    "pageToClipboard",
    "pageTitleToClipboard",
    "pageToClipboardEmacs",
    "pageToClipboardHTML",
    "pageToClipboardMarkdown",
    "pageToClipboardRST",
    "openFromClipboard",
    "openLinkExternal",
    "downloadLink",
    "toggleAlwaysOnTop",
    "toggleFullscreen",
    "makeMark",
    "restoreMark",
    "storeScrollPos",
    "restoreScrollPos",
    "startRecording",
    "stopRecording",
    "menuOpen",
    "menuTop",
    "menuBottom",
    "menuSelect",
    "menuClose",
    "useEnteredData",
    "nop",
    "p.start",
    "p.moveToMouse",
    "p.startVisualSelect",
    "p.inspectElement",
    "p.startOfPage",
    "p.insertAtPosition",
    "p.centerOfView",
    "p.startOfView",
    "p.endOfView",
    "p.endOfPage",
    "p.moveRightMax",
    "p.moveLeftMax",
    "p.storePos",
    "p.restorePos",
    "p.openAudio",
    "p.openFrame",
    "p.openImage",
    "p.openVideo",
    "p.openLink",
    "p.downloadAudio",
    "p.downloadFrame",
    "p.downloadImage",
    "p.downloadVideo",
    "p.downloadLink",
    "p.newtabAudio",
    "p.newtabFrame",
    "p.newtabImage",
    "p.newtabVideo",
    "p.newtabLink",
    "p.externalAudio",
    "p.externalFrame",
    "p.externalImage",
    "p.externalVideo",
    "p.externalLink",
    "p.copyImageBuffer",
    "p.copyAudio",
    "p.copyFrame",
    "p.copyImage",
    "p.copyVideo",
    "p.copyLink",
    "p.copyTitleAttr",
    "p.copyPageTitle",
    "p.splitAudio",
    "p.splitFrame",
    "p.splitImage",
    "p.splitVideo",
    "p.splitLink",
    "p.vsplitAudio",
    "p.vsplitFrame",
    "p.vsplitImage",
    "p.vsplitVideo",
    "p.vsplitLink",
    "p.openText",
    "p.downloadText",
    "p.newtabText",
    "p.externalText",
    "p.copyText",
    "p.searchText",
    "p.splitText",
    "p.vsplitText"
]
